### ISSUE TITLE
When the field's name is "S", the field is loaded wrongly

### ISSUE THREAD

**Issue by arairyoto** [Alonreznik/dynamodb-json#10]
When the name of field is "S", the field's is loaded wrongly.
`
{
  "hoge": {
     "M": {
        "hogehoge": {
            "S" : "1"
         },
        "S": {
            "S": "2"
        }
    }
}
`
should be loaded as;
`
{
    "hoge": {
        "hogehoge": "1",
        "S": "2"
    }
}
`
but the result is;
`
{
    "hoge": "2"
}
`

**Comment by renecouto** [comment]
Edit: My comment was wrong. The suggested fix would not work.

**Comment by Alonreznik** [comment]
Hi Guys 
Thanks for the comment.
I'll fix it very soon and let you know.

**Comment by jagadish432** [comment]
Hi @Alonreznik ,
is this fixed?
please let me know the status. Thanks in advance.

**Comment by Alonreznik** [comment]
Hi @jagadish432 .
Currently no, and there are some problems handling fields with "S" as key.
I would, as a recommendation, avoid using this kind of key in my dynamodb table. 
Unfortunately, currently it won't be fixed here.

Thanks

Alon

**Comment by imtiazmangerah** [comment]
If anyone requires this behaviour and cannot change their schema as suggested above, you can either use:

- TypeSerializer/TypeDeserializer directly from `boto3.dynamodb.types`

```python
from boto3.dynamodb.types import TypeDeserializer, TypeSerializer


deserializer = TypeDeserializer()
serializer = TypeSerializer()

def deserialize(document):
    return deserializer.deserialize({'M': document})

def serialize(value):
    return serializer.serialize(value)
```

- I have published a generic serialization / deserialization library with DynamoDB support called [cerealbox](https://github.com/a2d24/cerealbox).

Note - neither of these options convert to a json string directly. They behave similar to `dynamodb-json` with `as_dict=True`.

@Alonreznik apologies for hijacking this issue, just wanted to add in alternatives for the community since this issue is a wontfix.
